### ISSUE TITLE
[Feature] var syntax and user profile file

### ISSUE THREAD

**Issue by tkow** [MOCHI-inc-JAPAN/syncenv#26]
If config file has ${vars.VAR_NAME}, command option, --vars=VAR_NAME:val will replace ${vars.VAR_NAME} to val.
This feature's useful each user needs different configs. In addition, make it able to switch profile easily by `-p,--profile profile name` flag. Default profile names are defined by cosmiconfig and `.syncenv-profile.yml` is recommended, and make  --profile `filename:profilename` available.

```yaml
default:
  config: .syncenvrc.yaml
  vars:
    VAR_NAME: default
local:
  config: .syncenvrc.yaml
  vars:
    VAR_NAME: local
stg:
  config: .syncenvrc.stg.yaml
  vars:
    VAR_NAME: stg
```

The keys  of  the profile file are profile names.
